docs/_static/schemas/ipam_schema.yaml, pkg/ipamapis/apis/fic/v1/types.go
Update IPAM Spec and Status with Key
=> Add Schema file

pkg/controller/controller.go, pkg/ipamspec/ipamspec.go, pkg/manager/f5ipammanager.go, pkg/manager/manager.go, pkg/orchestration/kuberntes.go
=> Add Feature Key based IP Address Allocation

pkg/ipammachinery/ipam.go
=> Fixing ipam CRD schema

build-tools/_build-lib.sh, cmd/f5-ipam-controller/main.go
**Description**:  Added Version parameter to FIC and also prints version and buildInfo
=> Adding Version Info

pkg/provider/provider.go
Fixing the for sql db initialization
=> Fixing the for sql db initialization

docs/RELEASE-NOTES.rst
**Description**:  updating release notes for 0.1.3
=> Update 0.1.3 release notes

README.md, cmd/f5-ipam-controller/main.go, pkg/ipamapis/apis/fic/v1/types.go, pkg/manager/infobloxmanager.go, pkg/orchestration/kubernetes.go
**Description**:  Infoblox label processing with infoblox manager
**Changes Proposed in PR**: Infoblox label processing with infoblox manager
=> Infoblox label processing with infoblox manager

azure-pipelines.yml
**Description**:  Initialise docker tag to build version in azure pipeline
**Changes Proposed in PR**: Initialised docker tag to build version in azure pipeline
**Fixes**: internal
=> Initialise docker tag to build version in azure pipeline

azure-pipelines.yml, docs/RELEASE-NOTES.rst
**Description**:  Release notes for FIC 0.1.4 , CIS 2.5.0
* Changes svc connection name for scan account 
* Added conditional login to registries 
**Fixes**: internal
=> Release notes 0.1.4

azure-pipelines.yml
**Description**:  Modify minor release docker push step azure pipeline
**Changes Proposed in PR**: 
* Modified docker push script to be compatible with azure platform.
**Fixes**: internal
=> Modify minor release docker push step in azure pipeline

pkg/ipammachinery/fake.go
=> Add Fake Client for Unit Testing Support

Makefile, azure-pipelines.yml, build-tools/vet.sh
=> Azure CI changes for FIC

build-tools/Dockerfile.debian, build-tools/Dockerfile.debug, build-tools/Dockerfile.ubi
**Description**:  Enable CGO in Dockerfile for SQLite
**Changes Proposed in PR**: Enable CGO in Dockerfile for SQLite
**Fixes**: Internal crash
=> Enable CGO in Dockerfile for SQLite

Makefile
**Description**:  Disable fmt check for prod-quick
**Changes Proposed in PR**: remove verify target for prod-quick and add for prod
**Fixes**: -
=> Disable fmt check for prod-quick

README.md, build-tools/Dockerfile.debian, build-tools/Dockerfile.debug, build-tools/Dockerfile.ubi, pkg/provider/sqlite/store.go
**Description**:  Connect to DB using PV mount file
**Changes Proposed in PR**: replace in-memory SQLite connection with file based
**Fixes**: internal CONTCNTR-2872
=> Connect to DB using PV mount file

pkg/controller/controller.go, pkg/manager/f5ipammanager.go, pkg/manager/infobloxmanager.go, pkg/manager/manager.go, pkg/orchestration/kubernetes.go, pkg/provider/provider.go
**Changes Proposed in PR**: Dropping support for non-persistent providers.
=> Remove code that handles non-persistent default provider

pkg/orchestration/kubernetes.go, pkg/provider/sqlite/store.go
=> Handle stale status entries for IPAM resource

pkg/provider/provider.go, pkg/provider/sqlite/store.go
**Description**:  Fixes for unit test cases
=> Fixes for unit test cases

.gitlab-ci.yml, build-tools/_build-lib.sh
**Description**:  Updating pipeline for running unit testcases
=> Updating pipeline for running unit testcases

pkg/provider/provider.go
=> Fix label reuse issue with F5 IP provider

pkg/controller/controller_test.go, pkg/ipamapis/apis/fic/v1/types.go, pkg/ipamspec/ipamspec.go, pkg/manager/infobloxmanager.go, pkg/manager/manager.go, pkg/orchestration/kubernetes.go
=> Cleanup CIDR and DNSView from internal Requests

README.md, pkg/controller/controller.go, pkg/manager/infobloxmanager.go
**Description**:  _Disabling DNSView, but the logic and API is available, so that DNSView can be enabled easily in future, if needed._
=> Disable DNSView for Infoblox Provider

pkg/provider/sqlite/store.go
**Description**:  Sqlite update query fix for allocated IP address.
=> Bug fix: Sqlite update query fix

cmd/f5-ipam-controller/main.go, pkg/manager/infobloxmanager.go, pkg/manager/manager.go, pkg/orchestration/kubernetes.go, pkg/orchestration/mock/mockorchestrator.go, pkg/orchestration/orchestration.go
=> Add Trusted Certificates support for infoblox Provider

pkg/ipammachinery/ipam.go, pkg/manager/f5ipammanager.go, pkg/manager/infobloxmanager.go, pkg/orchestration/kubernetes.go, pkg/provider/sqlite/store.go
**Description**: 
FIC is reallocating IP address on IPAM controller restart when configured using static IP Address
- Fix DB queries, added error handling
**Fixes**: internal
=> Fix DB queries

pkg/provider/sqlite/store.go
**Description**:  Fix pending update DB query
**Changes Proposed in PR**: 
update DB query with proper syntax
**Fixes**: NA
=> Fix update DB query

cmd/f5-ipam-controller/main.go, pkg/manager/infobloxmanager.go, pkg/manager/manager.go, pkg/orchestration/kubernetes.go, pkg/orchestration/orchestration.go
**Description**:  Add support for infoblox custom cert
=> Add support for infoblox custom cert

docs/RELEASE-NOTES.rst
**Description**:  fic release notes
=> fic release notes v0.1.5

pkg/ipammachinery/ipam.go
**Description**:  update ipam schema for wildcard host pattern
=> update ipam schema for wildcard host pattern

docs/RELEASE-NOTES.rst, helm-charts/f5-ipam-controller/.helmignore, helm-charts/f5-ipam-controller/Chart.yaml, helm-charts/f5-ipam-controller/README.md, helm-charts/f5-ipam-controller/templates/NOTES.txt, helm-charts/f5-ipam-controller/templates/_helpers.tpl, helm-charts/f5-ipam-controller/templates/f5-ipam-controller-clusterrole.yaml, helm-charts/f5-ipam-controller/templates/f5-ipam-controller-clusterrolebinding.yaml, helm-charts/f5-ipam-controller/templates/f5-ipam-controller-deploy.yaml, helm-charts/f5-ipam-controller/templates/f5-ipam-controller-serviceaccount.yaml, helm-charts/f5-ipam-controller/values.yaml, helm-charts/labels.txt
=> Add Helm Charts support

docs/RELEASE-NOTES.rst, docs/faq/README.md
**Description**:  Adding FAQs and Troubleshooting steps
- added new faq folder under docs. 
- Updated Q&A
=> Adding FAQs and Troubleshooting steps

.github/ISSUE_TEMPLATE/bug_report.md, .github/pull_request_template.md, docs/faq/README.md
**Description**:  updated troubleshooting guide
- Updated the troubleshooting guide
- included it in new issue and PR template 
- added TOC using VSCode Markdown TOC plugin
=> Updated detailed steps in troubleshooting guide

helm-charts/f5-ipam-controller/README.md
Signed-off-by: Vivek Lohiya <vklohiya@live.com>
**Description**:  Updated the charts documentation
=> Updated the charts documentation

pkg/provider/provider.go, pkg/provider/sqlite/store.go
**Description**:  Handled crash caused due to failure in store initialisation, now FIC handling the crash gracefully.
**Changes Proposed in PR**: Handled crash caused due to failure in store initialisation
=> Handled crash in case of failure in store initialisation

docs/RELEASE-NOTES.rst
**Description**:  Updated Release Notes
**Changes Proposed in PR**: Updated Release Notes
=> Updating Release Notes

azure-pipelines.yml, f5-ipam-controller-operator/bundle.Dockerfile
**Description**:  helm chart and operator automation for FIC
=> chart automation

build-tools/Dockerfile.ubi
**Description**:  Mitigate Affected CVEs in FIC
**Changes Proposed in PR**: Mitigate Affected CVEs in FIC
=> Mitigate Affected CVEs

docs/RELEASE-NOTES.rst
Signed-off-by: Sravya Pondugula <sravyap135@gmail.com>
**Description**: 0.1.8 Release notes
=> 0.1.8 Release notes

helm-charts/f5-ipam-controller/Chart.yaml
Signed-off-by: Vivek Lohiya <vklohiya@live.com>
**Description**:  Updating the next version of helm chart
=> Updating the next version of helm chart

build-tools/Dockerfile.ubi
**Description**:  UBIRepoID Change
=> UBIRepoID Change

build-tools/Dockerfile.ubi
**Description**: Fix build failure
**Changes Proposed in PR**: Removed the package reference which are not installed in UBI anymore
=> Fix build failure

helm-charts/f5-ipam-controller/Chart.yaml
Signed-off-by: Vivek Lohiya <vklohiya@live.com>
**Description**:  Updating the versions for helm chart 0.0.3 release
=> Updating the versions for helm chart 0.0.3 release

helm-charts/f5-ipam-controller/Chart.yaml, helm-charts/f5-ipam-controller/README.md, helm-charts/f5-ipam-controller/templates/f5-ipam-controller-deploy.yaml, helm-charts/f5-ipam-controller/values.yaml
**Description**:  Support for infoblox credentials through k8s secrets
=> Support for infoblox credentials through k8s secrets

docs/RELEASE-NOTES.rst, pkg/orchestration/kubernetes.go
**Description**:  Fix IP deletion with CIS restart
**Changes Proposed in PR**: Fix IP deletion with CIS restart
**Fixes**: #2303 #2747
=> Fix IP deletion with CIS restart

docs/RELEASE-NOTES.rst
**Description**:  FIC 0.1.9 Release
=> FIC 0.1.9 Release

f5-ipam-controller-operator/Dockerfile, f5-ipam-controller-operator/bundle/manifests/f5-ipam-controller-operator.clusterserviceversion.yaml, f5-ipam-controller-operator/bundle/metadata/annotations.yaml, helm-charts/f5-ipam-controller/Chart.yaml
**Description**:  Upgraded the ipam operator to 4.15
**Changes Proposed in PR**: Upgraded the ipam operator to 4.15
**Fixes**: https://github.com/F5Networks/k8s-bigip-ctlr/issues/3419
=> upgrade operator to 4.15

build-tools/Dockerfile.ubi, f5-ipam-controller-operator/Dockerfile
=> fix: remove bash from build
